### PR TITLE
Support opening files inside wsl environments

### PR DESCRIPTION
**Pull request by soumyamahunt**

### CODE REVIEW

**Comment by JasonStein** [comment]
Is it WSL2?

**Comment by soumyamahunt** [comment]
> Is it WSL2?

Both should work, in wsl environments run

`powershell.exe /c notepads your/linux/path`

Use linux default path separater character if you are giving path without quotes.

**Comment by JasonStein** [comment]
should use  powershell.exe -c notepads instead /c to not block bash.

**Comment by soumyamahunt** [comment]
> should use powershell.exe -c notepads instead /c to not block bash.

[This issue](https://github.com/JasonStein/Notepads/issues/300) can be fixed using above command. Should mark it fixed.

**Pull request merged**
