### PR TITLE
Implemented moving lines up and down with Alt+Up/Down.

### PR DESCRIPTION
**Pull request by soumyamahunt**
Use Alt+Up/Down to move selected lines up/down respectively.

## PR Type
What kind of change does this PR introduce?

Feature

## Other information
gtrvHNS1wC

### CODE REVIEW

**Comment by soumyamahunt** [comment]
@JasonStein Plz check the implementation if it passes all cases. I haven't faced any issue so far.

**Comment by subodhpareek18** [comment]
@soumyamahunt oh wow, this is amazing, does it work for the current line too or just selection. By current line I mean where the cursor site currently.

**Comment by soumyamahunt** [comment]
> @soumyamahunt oh wow, this is amazing, does it work for the current line too or just selection. By current line I mean where the cursor site currently.

Yes, works that way too.

**Comment by JasonStein** [comment]
@soumyamahunt Found a bug, fixed here: https://github.com/JasonStein/Notepads/commit/9a18776b5ab2adc6c7a4743ebe89cfa31ce811f1

**Comment by JasonStein** [comment]
Found another issue:
image
Try Alt+Up and then Alt+Down

**Comment by soumyamahunt** [comment]
> Found another issue:
> image
> Replicate screenshot above and then try do Alt+Up and then Alt+Down

Fixed in #557.

**Pull request merged**
