### PR TITLE
Some Fixes

### PR DESCRIPTION
**Pull request by soumyamahunt**
These issues/requests have been added and should be closed:
[#236](https://github.com/JasonStein/Notepads/issues/236), [#197](https://github.com/JasonStein/Notepads/issues/197), [#17](https://github.com/JasonStein/Notepads/issues/17)

Also fixed AppBarButton, superscript toggle on "Ctrl+Shift+="

Added some new styles.

### CODE REVIEW

**Comment by soumyamahunt** [comment]
@JasonStein I noticed the RTL/LTR switch only works for current line. Is it intended behaviour??
Also Can you tell how periodic markdown rendering will be helpful compared to what we have now??

**Comment by JasonStein** [comment]
Hi @soumyamahunt , Can you separate your PR into small PRs? It is easier for me to review and I can put it on hold to decide which one to go in for each release. Since it will be harder to debug issues if we jam too many things in one release. Just my 2 cents. Thanks!

**Comment by JasonStein** [comment]
> @JasonStein I noticed the RTL/LTR switch only works for current line. Is it intended behaviour??
> Also Can you tell how periodic markdown rendering will be helpful compared to what we have now??

For RTL: you need to do ctrl+A first.
For periodic, if the markdown file is huge in size (thousand of lines), it will become super slow to edit anything if periodic fetching and rendering is not enabled. I have a sample code already to handle it. You can leave it to me.

**Comment by soumyamahunt** [comment]
> Hi @soumyamahunt , Can you separate your PR into small PRs? It is easier for me to review and I can put it on hold and decide which one to go in for each release. Since it will be harder to debug issues if we jam too many things in one release. Just my 2 cents. Thanks!

I have separated the pull requests, plz look into it when you have time.

> As well for the logging feature, If we add it, we should provide a setting for user to turn on and off. I still do not think it is a feature that will reach to most people. I want to keep Notepads as simple as it is at this current stage. Even for the markdown preview and diff viewer feature, there is only less than 5% of the user base have ever used.

I am thinking of adding a toggle in advanced settings section. Should I enable this feature by default??

**Comment by soumyamahunt** [comment]
> For periodic, if the markdown file is huge in size (thousand of lines), it will become super slow to edit anything if periodic fetching and rendering is not enabled. I have a sample code already to handle it. You can leave it to me.

Have you looked into [this](https://docs.microsoft.com/en-us/windows/communitytoolkit/controls/texttoolbar), might make your work easier.

**Pull request closed without merging**
