### PR TITLE
Implemented Print feature

### PR DESCRIPTION
**Pull request by soumyamahunt**
In hamburger flyout clicking the "Print" option or using "Ctrl+P" shortcut prompts printing content in current tab.
In hamburger flyout clicking the "Print All" option or using "Ctrl+Shift+P" shortcut prompts printing all the pages in a current window in a single prompt, each tab starts with a new page.
Modified mark down preview shortcut to "Alt+P" from "Ctrl+P".

### CODE REVIEW

**Comment by JasonStein** [comment]
Man, you are awesome! You deserve a medal!

**Comment by soumyamahunt** [comment]
> Man, you are awesome! You deserve a medal!

Thanks, I am happy to contribute.

**Comment by JasonStein** [comment]
So how did you come up with this implementation? I was not able to find a simple and good solution last year. Did you come up on your own?

**Comment by soumyamahunt** [comment]
> So how did you come up with this implementation? I was not able to find a simple and good solution last year. Did you come up on your own?

Used [this ](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Printing) sample app and did some changes.

**Comment by JasonStein** [comment]
> > So how did you come up with this implementation? I was not able to find a simple and good solution last year. Did you come up on your own?
> 
> Used [this ](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Printing) sample app and did some changes.

I was looking into the same but gave up in the middle since they covered too much in the sample... Glad you made it!

**Comment by JasonStein** [comment]
Do you have more PRs coming? (I am very curious).

**Comment by soumyamahunt** [comment]
> Do you have more PRs coming? (I am very curious).

I am not working on any feature right now, also most of the phase 2 is implemented. Any future ideas?? I am thinking on line numbering and syntax highlighting.

**Comment by JasonStein** [comment]
> > Do you have more PRs coming? (I am very curious).
> 
> I am not working on any feature right now, also most of the phase 2 is implemented. Any future ideas?? I am thinking on line numbering and syntax highlighting.

I would suggest you to take a look at this PR: https://github.com/JasonStein/Notepads/pull/271

The core logic is there, there is only one problem remining to be solved which is to make sure context menu gets recreated every time it opens. By design, the context menu does not support hot loading (changing structure like insert one menu item during runtime). We need to reconstruct the whole main menu on the fly to make it work. Currently, the menu is created using xaml not from code. On top of the PR I have, we need to delete the xaml and recreate/define menu items from code.

Let me know if you are interested.

**Comment by soumyamahunt** [comment]
> 
> I would suggest you to take a look at this PR: #271
> 
> The core logic is there, there is only one problem remining to be solved which is to make sure context menu gets recreated every time it opens. By design, the context menu does not support hot loading (changing structure like insert one menu item during runtime). We need to reconstruct the whole main menu on the fly to make it work. Currently, the menu is created using xaml not from code. On top of the PR I have, we need to delete the xaml and recreate/define menu items from code.
> 
> Let me know if you are interested.

Ok, I will look into it.

**Comment by JasonStein** [comment]
> > I would suggest you to take a look at this PR: #271
> > The core logic is there, there is only one problem remining to be solved which is to make sure context menu gets recreated every time it opens. By design, the context menu does not support hot loading (changing structure like insert one menu item during runtime). We need to reconstruct the whole main menu on the fly to make it work. Currently, the menu is created using xaml not from code. On top of the PR I have, we need to delete the xaml and recreate/define menu items from code.
> > Let me know if you are interested.
> 
> Ok, I will look into it.

https://social.msdn.microsoft.com/Forums/security/en-US/869ddb7f-271e-4ce3-88b2-b3734ed3e430/uwp-menuflyoutsubitem-items-collection-binding-problem?forum=wpdevelop

**Comment by JasonStein** [comment]
Two things I found:

1. By default, header has more space than footer
image

2. Pages per sheet is not working.
image

**Comment by soumyamahunt** [comment]
> 
> I would suggest you to take a look at this PR: #271
> 
> The core logic is there, there is only one problem remining to be solved which is to make sure context menu gets recreated every time it opens. By design, the context menu does not support hot loading (changing structure like insert one menu item during runtime). We need to reconstruct the whole main menu on the fly to make it work. Currently, the menu is created using xaml not from code. On top of the PR I have, we need to delete the xaml and recreate/define menu items from code.
> 
> Let me know if you are interested.

The only way I found the list to be updated is by removing the whole subitem and readding it to the flyout. Should I create a PR??

**Comment by soumyamahunt** [comment]
> 1. By default, header has more space than footer
>    image

I have fixed it will push later.
> 2. Pages per sheet is not working.
>    image

I don't have a printer to test on, can you tell what the option tries to do and what is the result??
> 3. I do not think public bool HaveNonemptyTextEditor() is necessary. There is no harm for user to print empty file/text.

The printpageformat method discards any pages which are empty. HaveNonEmptyTextEditor method is just a check to present print ui only if a non empty page exist. But you are right though, it can be combined with PrintAll method.

**Comment by JasonStein** [comment]
> > I would suggest you to take a look at this PR: #271
> > The core logic is there, there is only one problem remining to be solved which is to make sure context menu gets recreated every time it opens. By design, the context menu does not support hot loading (changing structure like insert one menu item during runtime). We need to reconstruct the whole main menu on the fly to make it work. Currently, the menu is created using xaml not from code. On top of the PR I have, we need to delete the xaml and recreate/define menu items from code.
> > Let me know if you are interested.
> 
> The only way I found the list to be updated is by removing the whole subitem and readding it to the flyout. Should I create a PR??

Yes, please go ahead.

**Comment by JasonStein** [comment]
> > 1. By default, header has more space than footer
> >    image
> 
> I have fixed it will push later.
> 
> > 1. Pages per sheet is not working.
> >    image
> 
> I don't have a printer to test on, can you tell what the option tries to do and what is the result??
> 
> > 1. I do not think public bool HaveNonemptyTextEditor() is necessary. There is no harm for user to print empty file/text.
> 
> The printpageformat method discards any pages which are empty. HaveNonEmptyTextEditor method is just a check to present print ui only if a non empty page exist. But you are right though, it can be combined with PrintAll method.

For testing, you can install Microsoft print to pdf driver, once that is installed, you should be able to use print feature and save output to a pdf file.

**Comment by soumyamahunt** [comment]
> > 1. I do not think public bool HaveNonemptyTextEditor() is necessary. There is no harm for user to print empty file/text.
> 
> The printpageformat method discards any pages which are empty. HaveNonEmptyTextEditor method is just a check to present print ui only if a non empty page exist. But you are right though, it can be combined with PrintAll method.

On second thought lets keep it as it is, removing it will require lots of changes.

**Comment by soumyamahunt** [comment]
> For testing, you can install Microsoft print to pdf driver, once that is installed, you should be able to use print feature and save output to a pdf file.

MS print to pdf isn't showing all the options, especially not the pages per sheet option.

**Comment by JasonStein** [comment]
> > For testing, you can install Microsoft print to pdf driver, once that is installed, you should be able to use print feature and save output to a pdf file.
> 
> MS print to pdf isn't showing all the options, especially not the pages per sheet option.

Forget about it, I can take a look to see how to fix it. You can focus on other things.

**Comment by soumyamahunt** [comment]
> 2. Pages per sheet is not working.
>    image

I installed the printer driver from [here ](https://www.colorpilot.com/emfprinterpilot.html) to test this and I can confirm it doesn't work. But I installed the [sample printing app](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Printing) and the feature doesn't work in it either. May be virtual printers can't print multiple pages per sheet, you need to have an actual printer for it. Or may be something wrong with the printing api.

**Comment by soumyamahunt** [comment]
> > 1. Pages per sheet is not working.
> >    image
> 
> I installed the printer driver from [here ](https://www.colorpilot.com/emfprinterpilot.html) to test this and I can confirm it doesn't work. But I installed the [sample printing app](https://github.com/Microsoft/Windows-universal-samples/tree/master/Samples/Printing) and the feature doesn't work in it either. May be virtual printers can't print multiple pages per sheet, you need to have an actual printer for it. Or may be something wrong with the printing api.

Tested with MS Word and the feature works on it. May be something wrong with printing api.

**Comment by soumyamahunt** [comment]
The screenshots in readme need to be changed to show the Markdown preview accelerator "Alt+P" instead of "Ctrl+P". I could do it myself but I don't how you took those cool looking screenshots with shadow border.

**Comment by JasonStein** [comment]
> The screenshots in readme need to be changed to show the Markdown preview accelerator "Alt+P" instead of "Ctrl+P". I could do it myself but I don't how you took those cool looking screenshots with shadow border.

Leave it to me, I can use photoshop to just change Ctrl to Alt accordingly.

**Comment by JasonStein** [comment]
Thanks, merging now and I will make some adjustments including removing StandardPrintTaskOptions.NUp option from the settings.

**Comment by soumyamahunt** [comment]
> Thanks, merging now and I will make some adjustments including removing StandardPrintTaskOptions.NUp option from the settings.

Since it's not working it would be a good idea to remove it.

**Comment by JasonStein** [comment]
Made some adjustments in this commit: https://github.com/JasonStein/Notepads/commit/88c4a4a132dba10b0bd3014b89bfc8f0aa81f787

Can you help take a look?

**Comment by soumyamahunt** [comment]
> Made some adjustments in this commit: [88c4a4a](https://github.com/JasonStein/Notepads/commit/88c4a4a132dba10b0bd3014b89bfc8f0aa81f787)
> 
> Can you help take a look?

LGTM.

**Pull request merged**
