### PR TITLE
Added moving text with Alt+Left/Right

### PR DESCRIPTION
**Pull request by soumyamahunt**
Added moving text with Alt+Left/Right arrrow.

## PR Type
What kind of change does this PR introduce?

Feature
## Other information
I found none of the windows' text editor has this feature but gnome-editor in Linux has this behavior so I added this to Notepads.
EwhtKXupjD
9h4kc6rnJO
32iFd3R077
kWyEcrsQDv
XtTHlqoSQt

### CODE REVIEW

**Comment by JasonStein** [comment]
There are some code used in MoveTextRight and Left can be move out of them for sharing. Can you make some refactoring here to reduce the length/complexity of the method?

**Comment by soumyamahunt** [comment]
@JasonStein reduced complexity in the methods.

**Comment by JasonStein** [comment]
Not sure if this is intended:
image
Click alt+right two times then do alt+left.

**Comment by soumyamahunt** [comment]
> @soumyamahunt
> Not sure if this is intended:
> image
> Click alt+right two times then do alt+left.

Yes this is intended behavior.

**Pull request merged**
