### PR TITLE
Set Notepads as default opener for unsupported file extensions

### PR DESCRIPTION
**Pull request by soumyamahunt**
Desktop extension to redirect file activation to notepads app to open unsupported file extension.

## PR Type
What kind of change does this PR introduce?

Feature

## Other information
User can choose to set the extension as default opener of file type if he wants to open  the file with Notepads. Also right click context menu can also be implemented this way.

### CODE REVIEW

**Comment by soumyamahunt** [comment]
@JasonStein this PR depends on #523. Also there are few issues that needs to be sorted out. 

1. The `StorageFile.GetFileFromPathAsync()` doesn't work for hidden files. Any direct way to handle file activation using [this](https://blog.magnusmontin.net/2019/05/10/handle-protocol-activation-and-redirection-in-packaged-apps/comment-page-1/?unapproved=14663&moderation-hash=1e278144ad52cb60833e0612391d3994#comment-14663) article.

2. Also launching with `Launcher.LaunchFileAsync()` doesn't work for unsupported extensions.

Any help regarding these issues??

**Comment by JasonStein** [comment]
> @JasonStein this PR depends on #523. Also there are few issues that needs to be sorted out.
> 
> 1. The `StorageFile.GetFileFromPathAsync()` doesn't work for hidden files. Any direct way to handle file activation using [this](https://blog.magnusmontin.net/2019/05/10/handle-protocol-activation-and-redirection-in-packaged-apps/) article.
> 2. Also launching with `Launcher.LaunchFileAsync()` doesn't work for unsupported extensions.
> 
> Any help regarding these issues??

I just did a quick implementation on file rename and I am also seeing that for renaming existing files. Basically, you cannot do rename from like "file.txt" to "file" or "file.unknown" if Notepads does not associate with ".unknown" extension. This is stupid as hell. However, rename "file.txt" to "file.md" is ok since ".md" is supported in package manifest.

**Comment by soumyamahunt** [comment]
> I just did a quick implementation on file rename and I am also seeing that for renaming existing files. Basically, you cannot do rename from like "file.txt" to "file" or "file.unknown" if Notepads does not associate with ".unknown" extension. This is stupid as hell. However, rename "file.txt" to "file.md" is ok since ".md" is supported in package manifest.

This is what happens in `LaunchFileAsync()` too. Only extensions associated with the app can be opened. The workaround I came up with was to pass file path via commandline and that requires `broadFileSystemAccess` to access file and it won't work for hidden files.

**Comment by soumyamahunt** [comment]
@JasonStein the progress so far:

40rew84VUl

**Comment by soumyamahunt** [comment]
Closing this in favor of #755.

**Pull request closed without merging**
