### PR TITLE
new app icon

### PR DESCRIPTION
**Pull request by mah-qurashy**

### CODE REVIEW

**Comment by JasonStein** [comment]
@mah-qurashy 

LargeTile.scale-150.png is kind of blurry, can you take a look?
Same for SmallTile.scale-100, SmallTile.scale-125, SmallTile.scale-150, Square44x44Logo.scale-125, Square150x150Logo.scale-150, StoreLogo.scale-125, StoreLogo.scale-150, Wide310x150Logo.scale-150.

**Comment by JasonStein** [comment]
@mah-qurashy Check how it looks at real scaling, don't scale it up.

**Comment by mah-qurashy** [comment]
> @mah-qurashy Check how it looks at real scaling, don't scale it up. Just use windows photo viewer.

yeah it looks blurry on the photos app, but it's not, i think the photos app is just acting weird, does it look fine in the browser?
> LargeTile scale-150.png

LargeTile scale-150
> SmallTile.scale-100

SmallTile scale-100

**Comment by JasonStein** [comment]
> > @mah-qurashy Check how it looks at real scaling, don't scale it up. Just use windows photo viewer.
> 
> yeah it looks blurry on the photos app, but it's not, i think the photos app is just acting weird, does it look fine in the browser?
> 
> > LargeTile scale-150.png
> 
> LargeTile scale-150
> 
> > SmallTile.scale-100
> 
> SmallTile scale-100

You are right, something is wrong with windows photo viewer, I tried another software and it looks good to me. Ready to check-in?

**Comment by JasonStein** [comment]
I am going to change the readme as below, let me know if this looks ok to you or let me know if you have better idea:

* Yi Zhou - App icon designer, Notepads App Icon (old) is greatly inspired by the new icon for Windows Terminal.
* Mahmoud Qurashy - App icon and file icon(s) designer,  creator of the new Notepads App Icon.

**Comment by mah-qurashy** [comment]
> @mah-qurashy
> I am going to change the README as below, let me know if this looks ok to you or let me know if you have better idea:
> 
> * Yi Zhou - App icon designer, Notepads App Icon (old) is greatly inspired by the new icon for Windows Terminal.
> * Mahmoud Qurashy - App icon and file icon(s) designer,  creator of the new Notepads App Icon.

thank you, I don't have any suggestions on that, it looks good to me.
looking forward to seeeing how the new icons look on the next release

**Comment by JasonStein** [comment]
> > @mah-qurashy
> > I am going to change the README as below, let me know if this looks ok to you or let me know if you have better idea:
> > 
> > * Yi Zhou - App icon designer, Notepads App Icon (old) is greatly inspired by the new icon for Windows Terminal.
> > * Mahmoud Qurashy - App icon and file icon(s) designer,  creator of the new Notepads App Icon.
> 
> thank you, I don't have any suggestions on that, it looks good to me.
> looking forward to seeeing how the new icons look on the next release

@mah-qurashy I think the white icons are little bit too grayish (looks quite dirty). What do you think? Do you mind brighten it a little bit and send out another PR?

Screen Shot 2020-05-02 at 2 20 02 AM

**Comment by JasonStein** [comment]
Screen Shot 2020-05-02 at 2 19 56 AM
Make this color a little bit brighten and whiter.

**Comment by mah-qurashy** [comment]
> Screen Shot 2020-05-02 at 2 19 56 AM
> 
> Make this color a little bit brighten and whiter?

it does look so on a white background, i tried to achieve a balance between looking good on dark and light backgrounds since this icon is used for both light/dark windows themes and would rarely appear on a purely white backgrounds (mostly taskbar and start tiles), i didn't want it to look too bright on dark theme
that being said i think it could use some more brightness, maybe i could make it the same color as the old icon and do some testing

**Comment by mah-qurashy** [comment]
as further thoughts, could we have the app icon change for global windows light/dark themes
it seems to be done in this screenshot for the windows store icon and older metro-style icons have that currently
windows-10-startmenu-livetiles-off 1
having the icon appear on either a dark or light background only could make it easier to decide whether to go more/less agressive with the brightness/contrast
also i noticed that the way notepads implements this (for the areas in which it's implemented) is reversed meaning the light icon w/ light theme and dark icon w/ dark theme, if this is the way to go then it would make sense to make the light icon brighter

**Comment by JasonStein** [comment]
> as further thoughts, could we have the app icon change for global windows light/dark themes
> it seems to be done in this screenshot for the windows store icon and older metro-style icons have that currently
> windows-10-startmenu-livetiles-off 1
> having the icon appear on either a dark or light background only could make it easier to decide whether to go more/less agressive with the brightness/contrast
> also i noticed that the way notepads implements this (for the areas in which it's implemented) is reversed meaning the light icon w/ light theme and dark icon w/ dark theme, if this is the way to go then it would make sense to make the light icon brighter

Let me investigate a little bit on how to align it with the new design for the tile background here. But we should just follow the store icon here: white on dark and dark on white background. I am fine with existing color scheme when it is actually used in the app for the icons, but maybe we can make it whiter for the ones that is been used on the website and README?

I am talking about these three for now:
image

**Comment by JasonStein** [comment]
Here you go:

image

image

image

image

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/commit/7f9ee8f761d48381fea65e45c3acdd5063060972

**Comment by mah-qurashy** [comment]
> I am talking about these three for now:
> image
will do it

> Here you go:
> 
> image
> 
> image
> 

are we unable to change the icon with the windows theme
it seems to be done on some apps but these are rather symbolic icons that windows could be simply auto masking to a dark color
image
however the windows store icon in the new start menu is not, so it could be something that microsoft is yet to add with the new tile style
if that is the case then fixing tile color should keep us good for the time being

**Comment by JasonStein** [comment]
@mah-qurashy Yes, it is all fake at this moment. We need to wait until Windows supports it. I am not seeing it coming anytime soon.

**Comment by mah-qurashy** [comment]
>could we have the app icon change for global windows light/dark themes

following on this, windows recently got the tiles update, then microsoft store icon was updated last week to have dark icon on the light tile, so maybe we can do this now
image

**Comment by soumyamahunt** [comment]
> following on this, windows recently got the tiles update, then microsoft store icon was updated last week to have dark icon on the light tile, so maybe we can do this now
> image

Is it not done automatically?? Right now taskbar icons are automatically chosen from themes, I guess same mechanism is going to be used for start too.

**Comment by mah-qurashy** [comment]
> Is it not done automatically?? Right now taskbar icons are automatically chosen from themes, I guess same mechanism is going to be used for start too.

no, i got that windows build and it does not do it automatically for notepads icon
i checked the assets folder of windows store and it has a new images provided that has `altform-colorful_theme-light` qualifier
image

**Comment by JasonStein** [comment]
> > Is it not done automatically?? Right now taskbar icons are automatically chosen from themes, I guess same mechanism is going to be used for start too.
> 
> no, i got that windows build and it does not do it automatically for notepads icon
> i checked the assets folder of windows store and it has new images that has `altform-colorful_theme-light` qualifier
> image

Feel free to add it.

**Pull request merged**
