### PR TITLE
2 new buttons

### PR DESCRIPTION
**Pull request by FJduFou**
contributors + downloads

### CODE REVIEW

**Comment by JasonStein** [comment]
I used to have the download link but it is not suitable for now since all users are going to Microsoft Store for app downloading of Notepads. There are not many traffic from release page now. 

For contributor, there is already a dedicated section, so no button is needed as well.

The most important reason is that there are already 4 badges there, 5 would be too much and no one will every care. Just my 2 cents here.

**Comment by FJduFou** [comment]
for the contributor, it is to have an overview
otherwise, for the download button, it is a question of seeing if it is a very downloaded application or not
especially since yours is very downloaded, it can perhaps encourage developers to participate in the project ...

**Comment by JasonStein** [comment]
Only few download notepads from the release page, the number won't be appealing. The star count is good enough for attracting developers, btw, I still prefer solo at this moment since I am still passionate about what I am doing right now. I would prefer to have a list of contributor icons down below readme.

**Comment by FJduFou** [comment]
Where exactly the contributors ?

**Comment by JasonStein** [comment]
I am referring to something like these:
image

**Comment by FJduFou** [comment]
ok

**Comment by FJduFou** [comment]
https://sourcerer.io
if you register in this, i think is possible

**Comment by JasonStein** [comment]
I have added hall-of-fame in the contributor section and tweak a little bit on readme.

**Comment by FJduFou** [comment]
okki

**Pull request closed without merging**
