### PR TITLE
Updated hu-HU translation

### PR DESCRIPTION
**Pull request by AmionSky**

### CODE REVIEW

**Comment by JasonStein** [comment]
two more here:

**Comment by AmionSky** [comment]
Where are those strings located?

**Comment by JasonStein** [comment]
https://github.com/JasonStein/Notepads/blob/c14dce99f0021cd4dcaeb0e0358a70db26867d4b/src/Notepads/Strings/hu-HU/Resources.resw#L149

**Comment by AmionSky** [comment]
Looks like I wasn't on the right commit. Updated it now with the settings translations as well but I was unable to test it, VS complains about `No certificate found with the supplied thumbprint` when I try to build it.

**Comment by JasonStein** [comment]
> Looks like I wasn't on the right commit. Updated it now with the settings translations as well but I was unable to test it, VS complains about `No certificate found with the supplied thumbprint` when I try to build it.

@validatedev is having the same issue with you. I need to check what went wrong here. I did not touch any build/config files recently to be clear. And I do not think certificate is required to build and run on dev box.

**Comment by JasonStein** [comment]
I think you just need to clear cache, restart VS and rebuild.

**Pull request merged**
