### PR TITLE
Update uk-UA strings

### PR DESCRIPTION
**Pull request by Tarik02**

### CODE REVIEW

**Comment by JasonStein** [comment]
Thanks! Can you update session snapshot description as well?
image

**Comment by Tarik02** [comment]
@JasonStein it is already in master :)

**Comment by JasonStein** [comment]
> @JasonStein it is already in master :)

Yes, but I added a reminder at the end of the description to notify user that session snapshot is disabled in shadow instances :)

**Comment by Tarik02** [comment]
Oh, sorry, will do

**Pull request merged**
